# -*- coding: utf-8 -*-
"""Per-suburb content attributes.

This is the file that stops 116 suburb pages being doorway spam. Every page's copy is
composed from these fields, and every field is a real, checkable characteristic of the
suburb that changes how an air conditioner actually gets installed there.

  profile   one of the install archetypes below - drives the technical angle
  stock     the dominant housing the installer will actually meet
  terrain   access / siting reality (steep block, crane, walk-up, laneway)
  local     two or three genuine local references (streets, parks, landmarks)
  hook      the single most distinctive install consideration, in one clause
  system    the system type that suits most homes here, and why

PROFILES
  coastal    salt-laden air, corrosion protection, outdoor-unit siting
  strata     apartments, body-corporate approval, noise limits, common property
  heritage   conservation area, nothing street-facing, concealed runs
  estate     large blocks, generous roof space, ducted is the obvious fit
  steep      split-level or waterfront, access and crane, multi-zone
  bush       bushland interface, long duct runs, leaf and ember debris
  postwar    low-pitch roofs, tight ceiling space, bulkheads or multi-head
  mixed      genuinely mixed stock, assessed case by case
"""

FACTS = {
# ─────────────────────────────────────────────── Eastern Suburbs
"bondi": dict(profile="coastal", stock="beachfront apartment blocks on Campbell Parade, walk-up units along Bondi Road, semis and federation homes behind",
  terrain="a slope from the beach up to Bondi Road, with rear-lane access on many streets",
  local=["Campbell Parade", "Bondi Road", "Hall Street"],
  hook="salt air reaches well back from the sand and works on an outdoor unit faster than anything inland",
  system="multi-head splits for the units, ducted for the houses behind the ridge"),
"bondi-beach": dict(profile="coastal", stock="1920s and 1930s walk-up flats, a handful of newer boutique blocks, very little detached housing",
  terrain="flat along the promenade, rising sharply at both headlands",
  local=["Bondi Pavilion", "Notts Avenue", "Campbell Parade"],
  hook="front-line salt exposure — an uncoated condenser here can show corrosion within a couple of summers",
  system="coastal-grade split systems with treated coils, sited away from the prevailing southerly"),
"bondi-junction": dict(profile="strata", stock="high-rise towers around the interchange, three- and four-storey red-brick walk-ups, terraces towards Queens Park",
  terrain="a ridge top, so most blocks are level but wind-exposed at height",
  local=["Oxford Street Mall", "Westfield", "the bus and rail interchange"],
  hook="the outdoor unit has to satisfy strata, noise clearances and condensate drainage all at once",
  system="multi-head splits running two or three rooms from one outdoor unit"),
"north-bondi": dict(profile="coastal", stock="post-war brick homes and duplexes on the hill, newer knock-down rebuilds closer to Ben Buckler",
  terrain="steep streets falling to the beach and to the golf links",
  local=["Ben Buckler", "Hastings Parade", "North Bondi RSL"],
  hook="exposed headland positions get the full brunt of the salt and the wind",
  system="ducted where the roof allows, splits where the ceiling space does not"),
"tamarama": dict(profile="coastal", stock="a small number of houses and low-rise flats on very steep ground above the beach",
  terrain="one of the steepest pockets in the east — access is the first thing we assess",
  local=["Tamarama Marine Drive", "the coastal walk", "Tamarama Park"],
  hook="steep driveways and split-level homes make outdoor-unit placement and crane access the whole job",
  system="multi-head splits, zoned to the levels the family actually uses"),
"bronte": dict(profile="coastal", stock="federation semis and cottages in the valley, apartments on the ridges either side",
  terrain="a valley running down to the beach, so homes sit at every angle to the sea",
  local=["Bronte Road", "Bronte Park", "the Bogey Hole"],
  hook="valley homes catch sea breeze and salt funnelled straight up from the beach",
  system="ducted for the cottages once roof space is checked, splits for the flats"),
"waverley": dict(profile="mixed", stock="federation and interwar houses, semis, and a steady run of unit blocks along Bronte Road",
  terrain="ridge-top, mostly level, with good roof access on the detached stock",
  local=["Waverley Park", "Bronte Road", "Waverley Cemetery"],
  hook="far enough back from the water to escape the worst salt, close enough to still need sensible siting",
  system="ducted suits the detached homes; the unit blocks are split-system territory"),
"clovelly": dict(profile="coastal", stock="interwar brick cottages and semis, low-rise flats near the beach",
  terrain="a steep valley to the bay with narrow streets and limited off-street parking",
  local=["Clovelly Road", "Burrows Park", "the Clovelly Bowling Club"],
  hook="narrow streets and steep blocks make equipment access as much of a factor as the system itself",
  system="ducted in the cottages, multi-head where roof space is tight"),
"coogee": dict(profile="coastal", stock="a large stock of walk-up units, art-deco blocks and semis, with houses climbing the hill behind",
  terrain="an amphitheatre around the bay, most properties with some sea aspect",
  local=["Arden Street", "Coogee Bay Road", "Dolphins Point"],
  hook="a big proportion of apartments means strata approval and salt protection in the same job",
  system="multi-head splits for units, ducted for the houses up the hill"),
"south-coogee": dict(profile="coastal", stock="post-war and modern detached homes, duplexes, few apartments",
  terrain="high, exposed clifftop streets with long ocean frontage",
  local=["Malabar Road", "Lurline Bay", "Trenerry Reserve"],
  hook="clifftop exposure is as harsh as it gets — coil treatment is not optional here",
  system="ducted where the roof pitch allows, coastal-grade outdoor units either way"),
"randwick": dict(profile="mixed", stock="grand federation homes near the racecourse, dense unit blocks towards the hospitals, terraces and semis between",
  terrain="broad and mostly level, with generous roof space on the older detached stock",
  local=["Royal Randwick", "The Spot", "Prince of Wales Hospital"],
  hook="two very different jobs in one suburb — heritage houses and high-turnover rental units",
  system="ducted for the federation stock, splits and multi-heads for the unit belt"),
"kensington": dict(profile="strata", stock="interwar semis and bungalows alongside a heavy concentration of student and investor apartments",
  terrain="gently sloping, level building platforms, easy access",
  local=["Anzac Parade", "UNSW", "Kensington Park"],
  hook="a lot of the work here is retrofitting units in blocks that were never designed for air conditioning",
  system="wall-mounted splits and multi-heads, sited to satisfy strata and the neighbours"),
"kingsford": dict(profile="strata", stock="red-brick walk-ups and newer infill apartments, with pockets of post-war brick houses",
  terrain="flat, with rear lanes serving many of the older blocks",
  local=["Anzac Parade", "Gardeners Road", "Kingsford Nine Ways"],
  hook="older walk-ups rarely have a tidy place for an outdoor unit — finding one is the job",
  system="multi-head splits, with the outdoor unit on a bracket or in the light well"),
"maroubra": dict(profile="coastal", stock="post-war brick homes and duplexes inland, unit blocks along the beach and Maroubra Road",
  terrain="a long slope from the beach up to the ridge at Maroubra Junction",
  local=["Maroubra Beach", "Anzac Parade", "Heffron Park"],
  hook="the suburb runs from beachfront to well inland, so salt exposure varies street by street",
  system="ducted inland, corrosion-protected splits nearer the sand"),
"matraville": dict(profile="postwar", stock="post-war brick and fibro homes on regular blocks, with newer duplex infill",
  terrain="flat and open, straightforward access",
  local=["Bunnerong Road", "Matraville Public School", "Jack Vanny Reserve"],
  hook="low-pitch post-war roofs are the constraint — ceiling space is often tighter than it looks",
  system="ducted where the roof allows, bulkhead or multi-head where it does not"),
"malabar": dict(profile="coastal", stock="post-war homes and duplexes, a small number of low-rise units near the bay",
  terrain="a bowl running down to Long Bay, with elevated streets on both sides",
  local=["Long Bay", "Malabar Beach", "Franklin Street"],
  hook="the bay funnels salt air inland, so protection matters further back than owners expect",
  system="ducted for detached homes, treated splits for the units"),
"little-bay": dict(profile="coastal", stock="modern master-planned townhouses and apartments on the former hospital site, plus older detached homes",
  terrain="open, elevated coastal land with new-estate access",
  local=["The Coast Golf Club", "Little Bay Beach", "Prince Henry"],
  hook="new builds often arrive without ducting provision even where the roof space is perfect",
  system="ducted retrofits in the townhouses, multi-head splits in the apartments"),
"paddington": dict(profile="heritage", stock="terrace rows almost end to end, with a small number of converted warehouses and flats",
  terrain="steep terraced streets, most homes with no side access at all",
  local=["Oxford Street", "Five Ways", "Paddington Reserve"],
  hook="a conservation area with no roof space and no side access — everything has to be concealed and craned or carried",
  system="multi-head splits with concealed line runs, or compact ducted in the roof cavity where one exists"),
"woollahra": dict(profile="heritage", stock="Victorian terraces and freestanding federation homes, a conservation area for most of its extent",
  terrain="rolling, with rear lanes behind most terrace rows",
  local=["Queen Street", "Moncur Street", "Cooper Park"],
  hook="heritage controls mean nothing visible from the street — outdoor units go to the rear or the lane",
  system="concealed ducted where the ceiling allows, otherwise discreet multi-head"),
"double-bay": dict(profile="strata", stock="luxury apartment blocks, a village core of shop-top housing, large homes on the ridges",
  terrain="a natural bowl to the harbour, level in the village and steep on the flanks",
  local=["Knox Street", "Transvaal Avenue", "Redleaf Pool"],
  hook="apartment work here is as much about presentation and noise as it is about capacity",
  system="ducted in the larger homes, quiet multi-head systems in the units"),
"bellevue-hill": dict(profile="estate", stock="large freestanding homes on substantial blocks, plus interwar apartment buildings along the main roads",
  terrain="one of the higher ridges in the east, with long views and windy elevated positions",
  local=["Victoria Road", "Cooper Park", "Bellevue Park"],
  hook="big homes, big roof spaces, and multi-storey layouts that genuinely need zoning",
  system="zoned ducted systems, often with a second unit for the upper level"),
"rose-bay": dict(profile="coastal", stock="waterfront apartments along New South Head Road, federation and modern homes on the hill",
  terrain="flat along the foreshore, climbing steeply to Bellevue Hill and Vaucluse",
  local=["Lyne Park", "New South Head Road", "the flying boat base"],
  hook="harbour-front does not mean salt-free — the outdoor unit still needs protection here",
  system="ducted on the hill, multi-head in the foreshore apartments"),
"vaucluse": dict(profile="steep", stock="large freestanding homes, many multi-level and built into the slope",
  terrain="very steep harbourside and clifftop blocks, frequently with crane or stair access only",
  local=["Vaucluse House", "Nielsen Park", "Hopetoun Avenue"],
  hook="multi-level homes on steep ground — zoning and equipment access drive the design",
  system="zoned ducted, often with more than one outdoor unit to shorten line runs"),
"watsons-bay": dict(profile="heritage", stock="a small, tightly held mix of cottages, semis and low-rise flats",
  terrain="a narrow peninsula, exposed on both the harbour and ocean sides",
  local=["Camp Cove", "The Gap", "Marine Parade"],
  hook="ocean on one side and harbour on the other — there is no sheltered aspect here",
  system="compact split systems with coastal-grade protection"),
"dover-heights": dict(profile="coastal", stock="post-war and rebuilt detached homes on a high clifftop grid",
  terrain="high, flat-topped and fully exposed to the easterly weather",
  local=["Rodney Reserve", "Military Road", "the Dover Heights cliff walk"],
  hook="clifftop wind and salt together are the harshest combination in the eastern suburbs",
  system="ducted with treated coils, outdoor unit sheltered on the western side"),
"point-piper": dict(profile="steep", stock="a very small number of large waterfront and near-waterfront homes",
  terrain="a steep harbour promontory, most homes stepping down the slope",
  local=["Wolseley Road", "Lady Martins Beach", "Wentworth Street"],
  hook="tight streets and steep frontages make access planning as important as the system",
  system="zoned ducted, discreetly placed plant"),
"darling-point": dict(profile="strata", stock="prestige apartment buildings alongside a handful of large freestanding homes",
  terrain="a steep harbour headland with limited street parking",
  local=["Darling Point Road", "McKell Park", "Yarranabbe Road"],
  hook="older prestige buildings with strict by-laws — approvals and plant location come before capacity",
  system="quiet multi-head systems, or ducted where the building allows"),
"edgecliff": dict(profile="strata", stock="high-rise and mid-rise apartments around the interchange, terraces on the streets behind",
  terrain="a ridge dropping sharply to Rushcutters Bay",
  local=["Edgecliff Centre", "New South Head Road", "Trumper Park"],
  hook="apartment density means strata approval, balcony and light-well siting, and noise limits",
  system="multi-head splits, sited to keep habitable rooms quiet"),
"rushcutters-bay": dict(profile="strata", stock="art-deco and 1960s apartment blocks around the park, some shop-top housing",
  terrain="flat around the bay, rising quickly on all three sides",
  local=["Rushcutters Bay Park", "the Cruising Yacht Club", "Bayswater Road"],
  hook="older blocks with no provision for outdoor units — placement is negotiated, not assumed",
  system="wall-mounted and multi-head splits with carefully planned line runs"),
"queens-park": dict(profile="mixed", stock="federation and interwar houses backing the park, semis and a few small unit blocks",
  terrain="gently sloping to the parkland, mostly level building platforms",
  local=["Queens Park", "York Road", "Centennial Parklands"],
  hook="quiet detached stock with usable roof space — one of the easier ducted suburbs in the east",
  system="zoned ducted systems"),
"centennial-park": dict(profile="heritage", stock="a very small residential pocket of grand homes bordering the parklands",
  terrain="level, leafy and tightly controlled",
  local=["Centennial Parklands", "Martin Road", "Lang Road"],
  hook="heritage-sensitive frontages with strict controls on anything visible from the street",
  system="concealed ducted with rear-sited plant"),
"eastgardens": dict(profile="postwar", stock="post-war brick homes, townhouse infill and apartments near the shopping centre",
  terrain="flat and open with easy vehicle access",
  local=["Westfield Eastgardens", "Bunnerong Road", "Heffron Park"],
  hook="low-pitch roofs on the original stock limit ducted options more often than not",
  system="ducted where the roof allows, bulkhead or multi-head elsewhere"),
"daceyville": dict(profile="heritage", stock="Australia's first government garden suburb — interwar cottages under a conservation overlay",
  terrain="flat, planned streets with consistent setbacks",
  local=["Daceyville Public School", "Banks Avenue", "the garden suburb layout"],
  hook="a heritage conservation area, so external changes are assessed on how visible they are",
  system="discreet split systems, plant to the rear"),
"moore-park": dict(profile="strata", stock="modern apartment developments and shop-top housing beside the sporting precinct",
  terrain="flat, with new-build service access",
  local=["the SCG", "Allianz Stadium", "Moore Park Golf"],
  hook="newer buildings often have provision, but capacity and balcony siting still need checking",
  system="split and multi-head systems within the building's approved locations"),

# ─────────────────────────────────────────────── Lower North Shore
"mosman": dict(profile="steep", stock="federation and interwar homes on large blocks, with apartment pockets around Military Road and Spit Junction",
  terrain="steep harbour-facing blocks, many with stair-only or crane access to the rear",
  local=["Military Road", "Balmoral Beach", "Taronga Zoo"],
  hook="steep harbourside blocks where getting the equipment to the plant location is half the job",
  system="zoned ducted for the houses, multi-head for the units"),
"cremorne": dict(profile="strata", stock="a dense band of interwar and 1960s apartment blocks, with federation homes towards the point",
  terrain="a ridge with steep fall to both Neutral and Shell Coves",
  local=["Military Road", "The Orpheum", "Cremorne Point"],
  hook="one of the highest apartment densities on the North Shore — strata approval is the first step",
  system="multi-head splits, with ducted reserved for the freestanding stock"),
"neutral-bay": dict(profile="strata", stock="walk-up and mid-rise apartments through the centre, semis and cottages on the side streets",
  terrain="ridge and gully, with plenty of split-level homes",
  local=["Military Road", "Hayberry Street", "Anderson Park"],
  hook="older walk-ups with no lift and no obvious plant location — access and siting drive the quote",
  system="wall-mounted and multi-head splits"),
"kirribilli": dict(profile="heritage", stock="art-deco apartment buildings and a small number of heritage houses",
  terrain="a steep harbour peninsula with very limited street access",
  local=["Kirribilli House", "Burton Street", "Jeffrey Street Wharf"],
  hook="heritage buildings and harbour views mean plant has to be invisible and quiet",
  system="compact multi-head systems with concealed runs"),
"milsons-point": dict(profile="strata", stock="high-rise apartments at the bridge approach, a handful of heritage terraces",
  terrain="steep and compact, with almost no off-street work space",
  local=["Luna Park", "the Harbour Bridge", "Alfred Street"],
  hook="high-rise work where crane access and building rules set the schedule, not the weather",
  system="multi-head and ducted cassette systems within building provisions"),
"north-sydney": dict(profile="strata", stock="commercial towers with residential blocks between them, plus pockets of terraces and semis",
  terrain="ridge-top and level through the CBD, falling away sharply north and south",
  local=["Miller Street", "North Sydney Oval", "Blues Point"],
  hook="a genuine mix of commercial fit-out and residential strata work in the same few blocks",
  system="ducted and cassette systems commercially, multi-head residentially"),
"mcmahons-point": dict(profile="steep", stock="terraces and cottages stepping down to the water, with apartment blocks at the ridge",
  terrain="very steep, narrow streets with harbour frontage",
  local=["Blues Point Road", "Lavender Bay", "Henry Lawson Avenue"],
  hook="narrow steep streets where equipment often has to be carried rather than driven in",
  system="compact splits and multi-heads"),
"waverton": dict(profile="mixed", stock="federation cottages and semis, with a few low-rise unit blocks near the station",
  terrain="undulating with harbour-side fall towards Balls Head",
  local=["Balls Head Reserve", "Bay Road", "Waverton station"],
  hook="tightly held federation stock where owners want the install to leave no trace",
  system="ducted through the roof cavity, plant to the rear"),
"wollstonecraft": dict(profile="mixed", stock="a mix of freestanding homes, semis and garden apartment blocks",
  terrain="leafy and sloping, with bushland reserve at the edges",
  local=["Berry Island Reserve", "Shirley Road", "Smoothey Park"],
  hook="leaf litter from the reserves clogs condensers faster here than in open suburbs",
  system="ducted for houses, splits for the unit stock, with serviceable plant placement"),
"crows-nest": dict(profile="strata", stock="terraces and workers cottages alongside a heavy band of apartments near the highway",
  terrain="ridge-top, level, with rear lanes behind many terrace rows",
  local=["Willoughby Road", "Hume Street Park", "the Pacific Highway"],
  hook="terraces with no side access and apartments with strict by-laws, often on the same street",
  system="multi-head splits, concealed runs, lane-side plant"),
"st-leonards": dict(profile="strata", stock="high-rise residential towers around the station and hospital, older cottages behind",
  terrain="ridge-top and level, dominated by tall buildings",
  local=["Royal North Shore Hospital", "the Pacific Highway", "Newlands Park"],
  hook="tower living with building-wide rules on penetrations and plant",
  system="multi-head and cassette systems within building provisions"),
"naremburn": dict(profile="mixed", stock="californian bungalows and federation cottages, largely detached, with newer rear additions",
  terrain="gently sloping, consistent blocks, good roof access",
  local=["Willoughby Road", "Naremburn Park", "Flat Rock Gully"],
  hook="consistent bungalow stock with real roof space — among the most straightforward ducted suburbs here",
  system="zoned ducted systems"),
"cammeray": dict(profile="mixed", stock="federation and interwar homes with a band of apartments along Miller Street",
  terrain="undulating, with the golf course and Tunks Park shaping the lower streets",
  local=["Miller Street", "Cammeray Golf Course", "Tunks Park"],
  hook="mixed stock where the same street can hold a bungalow and a walk-up block",
  system="ducted for the houses, multi-head for the flats"),
"northbridge": dict(profile="steep", stock="large freestanding homes, many split-level and built into the fall",
  terrain="steep bushland-edged blocks running down to Middle Harbour",
  local=["Sailors Bay Road", "Northbridge Golf Club", "Tunks Park"],
  hook="split-level homes on steep bush blocks where one system rarely serves every level well",
  system="zoned ducted, sometimes with a second system for the lower level"),
"willoughby": dict(profile="mixed", stock="californian bungalows and federation homes, with townhouses and units near the highway",
  terrain="mostly level ridge with gentle fall to the east",
  local=["Penshurst Street", "Willoughby Park", "the Incinerator"],
  hook="generous roof space on the bungalow stock makes ducted the default here",
  system="zoned ducted systems"),
"artarmon": dict(profile="mixed", stock="federation and interwar homes on the residential side, apartments near the station, light industry to the west",
  terrain="level, with easy access on most streets",
  local=["Hampden Road", "Artarmon Reserve", "Gore Hill"],
  hook="one suburb with genuinely different jobs — houses, apartments and commercial units",
  system="ducted residentially, cassette and split systems commercially"),
"chatswood": dict(profile="strata", stock="high-rise apartment towers through the centre, federation and post-war homes in the surrounding streets",
  terrain="level in the town centre, sloping away to the east and west",
  local=["Victoria Avenue", "Chatswood Chase", "the Concourse"],
  hook="tower strata rules on one side of the suburb and roomy federation roof spaces on the other",
  system="multi-head in the towers, zoned ducted in the houses"),
"lane-cove": dict(profile="mixed", stock="a dense band of walk-up and mid-rise apartments near the plaza, federation and post-war homes around it",
  terrain="a plateau falling to the river and to Stringybark Creek",
  local=["Longueville Road", "Lane Cove Plaza", "Lane Cove National Park"],
  hook="apartments near the village and bushland-edge homes at the fringes, each with a different problem",
  system="multi-head near the plaza, ducted on the residential streets"),
"lane-cove-north": dict(profile="mixed", stock="post-war homes and a substantial newer apartment precinct at Mowbray Road",
  terrain="gently undulating, with parkland to the north",
  local=["Mowbray Road", "Blackman Park", "Epping Road"],
  hook="new apartment stock alongside post-war houses with low-pitch roofs",
  system="splits in the new blocks, ducted or bulkhead in the older homes"),
"longueville": dict(profile="steep", stock="large freestanding homes on tightly held waterfront and near-waterfront blocks",
  terrain="a steep peninsula with narrow streets and water frontage",
  local=["Longueville Road", "Kingsford Smith Oval", "Woodford Bay"],
  hook="steep peninsula blocks where plant placement and line runs need planning before quoting",
  system="zoned ducted with carefully sited outdoor units"),
"riverview": dict(profile="bush", stock="large homes on bushland blocks, many backing directly onto reserve",
  terrain="steep, heavily treed and bordered by the Lane Cove River",
  local=["Saint Ignatius College", "Tambourine Bay", "Lane Cove River"],
  hook="bushland blocks mean leaf litter, longer duct runs and condensers that need regular clearing",
  system="zoned ducted, with serviceable plant clear of the canopy"),
"greenwich": dict(profile="steep", stock="federation homes and cottages on steep harbourside streets, with a small unit pocket",
  terrain="steep fall to the river on both sides of the ridge",
  local=["Greenwich Road", "Greenwich Wharf", "Gore Cove"],
  hook="steep streets and older homes with modest ceiling cavities",
  system="compact ducted where possible, multi-head where it is not"),
"hunters-hill": dict(profile="heritage", stock="sandstone and federation homes across one of Sydney's largest heritage conservation areas",
  terrain="a leafy peninsula with steep water-frontage streets",
  local=["Gladesville Bridge", "Boronia Park", "Woolwich Road"],
  hook="one of Sydney's strictest heritage areas — nothing visible from the street survives assessment",
  system="fully concealed ducted with plant screened at the rear"),
"woolwich": dict(profile="heritage", stock="a small peninsula of heritage homes and a few apartments",
  terrain="steep, narrow and surrounded by water on three sides",
  local=["Woolwich Dock", "Clarkes Point Reserve", "Woolwich Road"],
  hook="heritage controls and marine air in the same job",
  system="concealed ducted or discreet splits with protected coils"),
"castle-cove": dict(profile="bush", stock="post-war and modern split-level homes on bush blocks above Middle Harbour",
  terrain="steep, treed and bounded by Garigal National Park",
  local=["Deepwater Road", "Castle Cove Golf Club", "Middle Harbour"],
  hook="split-level bush homes where zoning matters and condensers fill with leaf litter",
  system="zoned ducted with accessible outdoor plant"),
"middle-cove": dict(profile="bush", stock="detached split-level homes on large bushland blocks",
  terrain="steep and heavily treed, backing onto reserve",
  local=["Sugarloaf Bay", "Harold Reid Reserve", "Eastern Valley Way"],
  hook="long duct runs across split levels, and plant that has to stay clear of the canopy",
  system="zoned ducted systems"),
"roseville-chase": dict(profile="bush", stock="post-war and modern homes on sloping bush blocks near Middle Harbour",
  terrain="steep, treed and close to the waterway",
  local=["Babbage Road", "Echo Point", "Garigal National Park"],
  hook="bushland setting with real debris load on outdoor units",
  system="ducted with serviceable, clear-standing plant"),
"castlecrag": dict(profile="bush", stock="Griffin-designed and modernist homes on bush blocks, many heritage-listed",
  terrain="steep, rocky and heavily treed with narrow winding streets",
  local=["The Griffin houses", "Edinburgh Road", "Sugarloaf Bay"],
  hook="architecturally significant homes where the install must not read on the building at all",
  system="concealed ducted, plant sited off the sightlines"),

# ─────────────────────────────────────────────── Upper North Shore & Hornsby
"roseville": dict(profile="estate", stock="federation and californian bungalows on wide blocks, with a small unit pocket near the station",
  terrain="level to gently sloping, leafy streets with mature trees",
  local=["Hill Street", "Roseville Park", "the Pacific Highway"],
  hook="classic upper North Shore roof space — ducted is nearly always the right answer",
  system="zoned ducted systems"),
"lindfield": dict(profile="estate", stock="large federation and interwar homes on generous blocks, apartments near the station",
  terrain="undulating, leafy, with deep setbacks",
  local=["Lindfield Avenue", "Tryon Road", "Queen Elizabeth Reserve"],
  hook="big homes with multiple living zones — a single-zone system leaves half the house wrong",
  system="zoned ducted, typically six to eight zones"),
"killara": dict(profile="estate", stock="large federation and Victorian homes on some of the biggest blocks on the line",
  terrain="gently undulating with heavy tree cover and long driveways",
  local=["Springdale Road", "Killara Golf Club", "Fiddens Wharf Road"],
  hook="heritage-era homes with slate and tile roofs that need care during install",
  system="zoned ducted with careful roof access"),
"east-killara": dict(profile="bush", stock="post-war and modern homes on the bushland side of the ridge",
  terrain="sloping to the Lane Cove valley with reserve frontage",
  local=["Koola Avenue", "Lane Cove National Park", "Allan Small Park"],
  hook="bushland-edge homes with leaf load and longer duct runs",
  system="zoned ducted systems"),
"gordon": dict(profile="estate", stock="federation homes on large blocks, with a growing apartment cluster around the station",
  terrain="ridge-top, mostly level, with fall to the east and west",
  local=["the Pacific Highway", "Gordon Golf Club", "Ravenswood"],
  hook="large family homes where zoning and quiet running matter more than headline capacity",
  system="zoned ducted with a quiet indoor fan coil"),
"pymble": dict(profile="estate", stock="substantial federation and interwar homes on very large, heavily treed blocks",
  terrain="undulating with deep gullies towards the national park",
  local=["Pymble Ladies College", "Avondale Golf Club", "Grandview Street"],
  hook="big multi-level homes and long duct runs — design matters more than equipment here",
  system="multi-zone ducted, sometimes two systems"),
"turramurra": dict(profile="estate", stock="federation and post-war family homes on large blocks, with units near the station",
  terrain="a broad ridge falling away steeply to Ku-ring-gai Chase on the north",
  local=["Rohini Street", "Karuah Park", "Ku-ring-gai Chase National Park"],
  hook="generous roof space, but long runs to reach the far ends of these homes",
  system="zoned ducted, planned around real room use"),
"north-turramurra": dict(profile="bush", stock="post-war and modern homes on large bush blocks close to the national park",
  terrain="elevated and heavily treed, bordering Ku-ring-gai Chase",
  local=["Bobbin Head Road", "North Turramurra Golf", "Ku-ring-gai Chase"],
  hook="bushfire-interface blocks where debris and ember screening affect outdoor unit siting",
  system="zoned ducted with protected, clear-standing plant"),
"south-turramurra": dict(profile="bush", stock="mid-century and modern homes on sloping blocks backing Lane Cove National Park",
  terrain="steep, treed, with reserve frontage on many streets",
  local=["Kissing Point Road", "Comenarra Parkway", "Lane Cove National Park"],
  hook="split-level homes on bush blocks — zoning and access both matter",
  system="zoned ducted systems"),
"warrawee": dict(profile="estate", stock="very large federation and Victorian homes on estate-sized blocks, many heritage-listed",
  terrain="level to gently sloping with mature gardens and long driveways",
  local=["the Pacific Highway", "Warrawee station", "Knox Grammar"],
  hook="heritage homes where roof access and slate tiling need an installer who has done it before",
  system="multi-zone ducted with concealed grilles"),
"wahroonga": dict(profile="estate", stock="large federation and interwar homes on wide blocks, with a heritage precinct around the station",
  terrain="ridge-top and leafy, with steep fall to the north",
  local=["Redleaf Avenue", "Wahroonga Park", "Abbotsleigh"],
  hook="big homes, heritage streets and mature trees — plant siting has to respect all three",
  system="zoned ducted with discreet outdoor plant"),
"st-ives": dict(profile="estate", stock="post-war and modern family homes on large blocks, with townhouse pockets near the shops",
  terrain="elevated plateau with bushland reserve on three sides",
  local=["Mona Vale Road", "St Ives Shopping Village", "Ku-ring-gai Wildflower Garden"],
  hook="big, open-plan family homes where zoning is what makes the system efficient",
  system="zoned ducted, six zones and up"),
"st-ives-chase": dict(profile="bush", stock="detached homes on large bush blocks against the national park",
  terrain="heavily treed and sloping, with bushfire-interface frontage",
  local=["Warrimoo Avenue", "Ku-ring-gai Chase National Park", "Cowan Creek"],
  hook="bushfire-interface siting and heavy leaf load on outdoor units",
  system="zoned ducted with screened, serviceable plant"),
"waitara": dict(profile="strata", stock="a dense apartment precinct around the station and hospital, with post-war houses behind",
  terrain="ridge-top and level, dominated by mid-rise blocks",
  local=["Hornsby Hospital", "the Pacific Highway", "Waitara Oval"],
  hook="apartment density means by-laws, balcony siting and noise limits before anything else",
  system="multi-head splits within the building's approved locations"),
"hornsby": dict(profile="mixed", stock="apartment towers around the station and Westfield, with post-war and federation homes spreading out from there",
  terrain="a ridge with steep fall to the east into the national park",
  local=["Westfield Hornsby", "the Water Clock", "Hornsby Park"],
  hook="the top of the line — tower strata on one side, big detached homes with real roof space on the other",
  system="multi-head in the towers, zoned ducted in the houses"),
"normanhurst": dict(profile="postwar", stock="post-war brick homes and californian bungalows on regular blocks",
  terrain="gently sloping and leafy, straightforward access",
  local=["Normanhurst Boys High", "Denman Parade", "the Pacific Highway"],
  hook="post-war roofs with lower pitch — ceiling space is the first thing to check",
  system="ducted where the roof allows, bulkhead or multi-head where it does not"),
"thornleigh": dict(profile="postwar", stock="post-war and 1970s homes on good-sized blocks, with townhouse infill",
  terrain="undulating with bushland gullies to the west",
  local=["Thornleigh Oval", "Pennant Hills Road", "Ruddock Park"],
  hook="mixed roof pitches across the same street, so no two quotes here are identical",
  system="ducted for the higher-pitch stock, multi-head elsewhere"),
"pennant-hills": dict(profile="bush", stock="post-war and federation homes on large treed blocks, with units near the station",
  terrain="undulating and heavily treed, bordering Lane Cove National Park",
  local=["Pennant Hills Park", "Britannia Street", "Lane Cove National Park"],
  hook="big treed blocks where condensers fill with leaf litter through autumn",
  system="zoned ducted with accessible plant"),
"beecroft": dict(profile="estate", stock="federation and interwar homes on large blocks in a heritage conservation area",
  terrain="leafy and undulating with deep bushland gullies",
  local=["Beecroft Village", "Chilworth Reserve", "Cheltenham Road"],
  hook="a conservation area with large period homes — concealed work and careful roof access",
  system="zoned ducted with concealed grilles"),
"cheltenham": dict(profile="estate", stock="large federation homes on generous blocks, tightly held and leafy",
  terrain="gently sloping with reserve frontage on several streets",
  local=["Cheltenham Oval", "The Crescent", "Devlins Creek"],
  hook="period homes with high ceilings that reward proper zoning and sizing",
  system="multi-zone ducted"),
"asquith": dict(profile="postwar", stock="post-war brick and fibro homes with newer duplex and townhouse infill",
  terrain="gently undulating with bushland to the east",
  local=["Asquith Oval", "the Pacific Highway", "Asquith Golf Club"],
  hook="low-pitch post-war roofs where ducted is not always feasible",
  system="multi-head splits, or ducted where the roof cavity allows"),
"mount-colah": dict(profile="bush", stock="detached homes on large bush blocks, many backing the national park",
  terrain="elevated, heavily treed, with bushfire-interface frontage",
  local=["Ku-ring-gai Chase National Park", "Mount Colah Oval", "the Pacific Highway"],
  hook="bushfire-interface property where plant siting and ember screening matter",
  system="zoned ducted with protected outdoor units"),
"berowra": dict(profile="bush", stock="detached homes on large bushland blocks, some with water access to the Hawkesbury",
  terrain="steep, heavily treed and surrounded by national park",
  local=["Berowra Waters", "Berowra Valley National Park", "Berowra Oval"],
  hook="the far end of the line — bushfire exposure, long driveways and heavy leaf load",
  system="zoned ducted with screened, serviceable plant"),

# ─────────────────────────────────────────────── Northern Beaches
"manly": dict(profile="coastal", stock="art-deco and modern apartment blocks near the beach, federation cottages and semis behind",
  terrain="a narrow isthmus between ocean and harbour, so salt comes from both sides",
  local=["The Corso", "Manly Beach", "Shelly Beach"],
  hook="ocean on one side and harbour on the other — there is no sheltered aspect in Manly",
  system="corrosion-protected splits and multi-heads, ducted in the cottages"),
"fairlight": dict(profile="coastal", stock="interwar flats and federation homes on a steep harbour slope",
  terrain="steep fall to the harbour with narrow streets",
  local=["Fairlight Beach", "Lauderdale Avenue", "the Manly to Spit walk"],
  hook="harbourside salt and steep access in the same job",
  system="multi-head splits with treated coils"),
"balgowlah": dict(profile="mixed", stock="post-war and federation homes with a strong apartment cluster around Stockland",
  terrain="undulating, with the ridge falling to both the harbour and Manly",
  local=["Stockland Balgowlah", "Sydney Road", "Balgowlah Oval"],
  hook="far enough from the surf to ease the salt load, close enough to still plan for it",
  system="ducted for houses, multi-head for the units"),
"balgowlah-heights": dict(profile="steep", stock="large detached homes on steep harbour-facing blocks",
  terrain="steep, elevated and heavily treed, with harbour views",
  local=["Dobroyd Head", "Tania Park", "Beatty Street"],
  hook="steep multi-level homes where zoning and equipment access both drive the design",
  system="zoned ducted, sometimes with two outdoor units"),
"seaforth": dict(profile="steep", stock="split-level and modern detached homes on steep blocks above Middle Harbour",
  terrain="very steep with bushland reserve and water frontage",
  local=["Seaforth Oval", "Bantry Bay", "Sydney Road"],
  hook="split-level homes on steep bush blocks — one thermostat will never suit the whole house",
  system="zoned ducted with per-level control"),
"clontarf": dict(profile="steep", stock="a small pocket of detached homes on steep waterfront and near-waterfront blocks",
  terrain="steep, treed and fronting Middle Harbour",
  local=["Clontarf Reserve", "Sandy Bay", "the Spit Bridge"],
  hook="waterfront blocks with limited access and real marine exposure",
  system="zoned ducted with corrosion-protected plant"),
"freshwater": dict(profile="coastal", stock="interwar cottages and semis, with unit blocks on the streets above the beach",
  terrain="a valley to the beach with steep streets on both sides",
  local=["Freshwater Beach", "Lawrence Street", "Harbord Diggers"],
  hook="beachside valley where salt air settles and lingers",
  system="treated splits near the sand, ducted further up the hill"),
"curl-curl": dict(profile="coastal", stock="post-war and rebuilt detached homes, with low-rise flats near the lagoon",
  terrain="flat near the lagoon, rising to the headland",
  local=["Curl Curl Beach", "Curl Curl Lagoon", "Greendale Creek"],
  hook="direct beach frontage and a lagoon that keeps the air humid",
  system="coastal-grade splits and ducted with treated coils"),
"north-curl-curl": dict(profile="coastal", stock="post-war brick homes and duplexes on the hill above the beach",
  terrain="elevated and exposed, sloping to the lagoon",
  local=["North Curl Curl Beach", "John Fisher Park", "Abbott Road"],
  hook="exposed elevation catches both the salt and the southerly",
  system="ducted with protected outdoor plant"),
"dee-why": dict(profile="strata", stock="a dense band of apartment towers along the beachfront and Pittwater Road, with post-war homes inland",
  terrain="flat along the beach, rising steeply to the Dee Why headland",
  local=["Dee Why Beach", "Pittwater Road", "Dee Why Lagoon"],
  hook="beachfront apartment density — strata approval and salt protection in the same job",
  system="multi-head splits in the towers, ducted in the homes inland"),
"narraweena": dict(profile="postwar", stock="post-war brick and fibro homes on a high inland ridge",
  terrain="elevated and open, with easy street access",
  local=["Narraweena Oval", "Alfred Road", "Cromer Heights"],
  hook="low-pitch post-war roofs are the recurring constraint here",
  system="ducted where the cavity allows, multi-head where it does not"),
"cromer": dict(profile="postwar", stock="post-war homes and duplexes with newer infill, plus a light-industrial pocket",
  terrain="undulating, bordered by Narrabeen Lagoon and bushland",
  local=["Cromer Golf Club", "Narrabeen Lagoon", "South Creek Road"],
  hook="mixed residential and small-commercial work in the same suburb",
  system="ducted and split systems residentially, cassettes commercially"),
"collaroy": dict(profile="coastal", stock="beachfront apartment blocks and post-war homes climbing the plateau behind",
  terrain="a narrow beachfront strip with a steep rise to Collaroy Plateau",
  local=["Collaroy Beach", "Pittwater Road", "Long Reef"],
  hook="front-line beach exposure on one street and sheltered elevation two streets back",
  system="treated splits at the beach, ducted on the plateau"),
"narrabeen": dict(profile="coastal", stock="a mix of beachside units, post-war homes and lakeside properties",
  terrain="between ocean and lagoon, mostly low-lying",
  local=["Narrabeen Lagoon", "Narrabeen Beach", "Ocean Street"],
  hook="salt from the ocean and humidity from the lagoon on the same block",
  system="corrosion-protected systems, sized for the humidity load"),
"north-narrabeen": dict(profile="coastal", stock="post-war homes, duplexes and low-rise units between the lagoon and the beach",
  terrain="flat and low-lying with water on two sides",
  local=["North Narrabeen Rock Pool", "Narrabeen Lagoon", "Powderworks Road"],
  hook="consistently humid, salt-laden air year round",
  system="treated coils and properly sized dehumidification capacity"),
"mona-vale": dict(profile="coastal", stock="post-war and modern homes, with unit blocks near the village and the beach",
  terrain="a plain between the beach and the escarpment, largely level",
  local=["Mona Vale Beach", "Barrenjoey Road", "Mona Vale Hospital"],
  hook="a service hub for the northern peninsula, with genuine beachside salt exposure",
  system="ducted for the homes, treated splits nearer the sand"),
"newport": dict(profile="coastal", stock="detached homes on the hill and beachfront units on the flat",
  terrain="steep hillsides falling to both Pittwater and the ocean",
  local=["Newport Beach", "Barrenjoey Road", "Bungan Head"],
  hook="ocean on one side, Pittwater on the other, and steep blocks between them",
  system="zoned ducted on the hill, treated splits on the flat"),
"avalon-beach": dict(profile="coastal", stock="beach cottages, modern rebuilds and low-rise units around the village",
  terrain="a valley between two headlands, with steep bush blocks either side",
  local=["Avalon Beach", "Old Barrenjoey Road", "Careel Bay"],
  hook="beach valley homes with bushland behind — salt from the front, leaf litter from the back",
  system="ducted with treated coils and accessible plant"),
"palm-beach": dict(profile="coastal", stock="large detached homes on steep blocks, many used seasonally",
  terrain="a steep peninsula with ocean on one side and Pittwater on the other",
  local=["Barrenjoey Lighthouse", "Palm Beach Wharf", "Ocean Road"],
  hook="the most exposed position on the peninsula, and often unoccupied for weeks at a time",
  system="zoned ducted with marine-grade protection and remote monitoring"),
"bilgola-plateau": dict(profile="bush", stock="modern and mid-century homes on elevated bush blocks",
  terrain="high plateau with steep treed fall on both sides",
  local=["Bilgola Beach", "Plateau Road", "Bilgola Bends"],
  hook="elevated bush blocks with leaf load and long driveways",
  system="zoned ducted with clear-standing plant"),
"warriewood": dict(profile="mixed", stock="newer estate housing and townhouses alongside older homes and a business park",
  terrain="a valley behind the beach, largely level",
  local=["Warriewood Beach", "Warriewood Square", "Narrabeen Lagoon"],
  hook="newer estate homes often have the roof space but no ducting provision",
  system="ducted retrofits, splits in the townhouses"),
"frenchs-forest": dict(profile="postwar", stock="post-war and 1970s brick homes on regular blocks, with the hospital precinct at its centre",
  terrain="elevated plateau, bordered by Garigal National Park",
  local=["Northern Beaches Hospital", "Warringah Road", "Forestville RSL"],
  hook="1970s roofs with variable pitch and a lot of original insulation to work around",
  system="ducted where the cavity allows, multi-head where it does not"),
"belrose": dict(profile="bush", stock="1970s and modern detached homes on large bush blocks",
  terrain="elevated and heavily treed, bordering Garigal National Park",
  local=["Glenrose Village", "Garigal National Park", "Forest Way"],
  hook="bushfire-interface blocks with heavy leaf load on outdoor units",
  system="zoned ducted with screened, serviceable plant"),
"forestville": dict(profile="postwar", stock="post-war brick homes on regular blocks with newer rear additions",
  terrain="gently undulating with bushland gullies at the edges",
  local=["Forestville Shopping Village", "Bantry Bay Road", "Garigal National Park"],
  hook="consistent post-war stock where roof pitch decides ducted or not",
  system="ducted where possible, multi-head as the fallback"),
"beacon-hill": dict(profile="postwar", stock="post-war brick homes on an elevated ridge, many with district views",
  terrain="high and exposed, with steep streets on the flanks",
  local=["Beacon Hill Reserve", "Willandra Road", "Manly Dam"],
  hook="elevated and wind-exposed, with low-pitch post-war roofs",
  system="ducted where the cavity allows, otherwise multi-head"),
"allambie-heights": dict(profile="postwar", stock="post-war and 1970s homes on sloping blocks above Manly Dam",
  terrain="undulating and treed, bordering the Manly Dam reserve",
  local=["Manly Dam", "Allambie Heights Oval", "Kentwell Road"],
  hook="reserve-edge homes with leaf litter and mixed roof pitches",
  system="ducted or multi-head depending on the roof cavity"),
"brookvale": dict(profile="mixed", stock="post-war homes and newer apartments alongside the beaches' main industrial and retail precinct",
  terrain="flat and open with good vehicle access",
  local=["Warringah Mall", "Brookvale Oval", "Pittwater Road"],
  hook="the commercial heart of the beaches — as much shop and warehouse work as residential",
  system="cassette and ducted systems commercially, splits residentially"),
"queenscliff": dict(profile="coastal", stock="interwar flats and semis on a narrow strip between the beach and the lagoon",
  terrain="low-lying and hemmed in, with limited street access",
  local=["Queenscliff Beach", "Manly Lagoon", "the Queenscliff bridge"],
  hook="front-line salt exposure with lagoon humidity behind it",
  system="coastal-grade splits with treated coils"),
"north-manly": dict(profile="postwar", stock="post-war brick homes and duplexes inland of the lagoon",
  terrain="flat and low-lying beside Manly Lagoon",
  local=["Manly Lagoon", "Kentwell Road", "Griffiths Park"],
  hook="low-lying and humid, with post-war roof cavities to work within",
  system="ducted where the roof allows, multi-head elsewhere"),
"terrey-hills": dict(profile="bush", stock="large properties and acreage on the plateau, some semi-rural",
  terrain="high, flat plateau surrounded by national park",
  local=["Terrey Hills Village", "Ku-ring-gai Chase National Park", "Mona Vale Road"],
  hook="large homes on acreage where duct runs get long and bushfire siting matters",
  system="multi-zone ducted, sometimes two systems for a single home"),
"davidson": dict(profile="bush", stock="1970s and modern detached homes on bush blocks against Garigal National Park",
  terrain="elevated and heavily treed with reserve frontage",
  local=["Garigal National Park", "Davidson Park", "Warringah Road"],
  hook="national-park frontage brings both leaf load and bushfire considerations",
  system="zoned ducted with protected, accessible plant"),
}
