/**
 * Google Places (New) proxy.
 *
 * The browser never sees the Google API key — it calls this endpoint, which
 * signs the request server-side. Two actions share one function:
 *
 *   POST { action: 'autocomplete', input, sessionToken }  -> suggestion list
 *   POST { action: 'details', placeId, sessionToken }     -> structured address
 *
 * `sessionToken` is generated by the client, reused across every keystroke of a
 * single lookup, and retired once details are fetched. Google bills that whole
 * run as one "Autocomplete (includes Place Details)" session rather than one
 * charge per keystroke, so a typical lead costs a single session.
 */

const allowedOrigins = (process.env.CORS_ALLOW_ORIGIN || process.env.ALLOWED_ORIGIN || '*')
  .split(',')
  .map((o) => o.trim())
  .filter(Boolean);

const setCors = (res: any, requestOrigin?: string) => {
  // Echo the caller's origin when it is on the allow-list, so a comma-separated
  // list (apex + www + preview) works instead of only the first entry.
  const allow =
    allowedOrigins.includes('*')
      ? '*'
      : requestOrigin && allowedOrigins.includes(requestOrigin)
        ? requestOrigin
        : allowedOrigins[0] || '*';
  res.setHeader('Access-Control-Allow-Origin', allow);
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Vary', 'Origin');
};

// Best-effort throttle. Serverless instances are recycled so this is not a hard
// guarantee, but it stops a naive script from burning the Places quota.
const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX = 60;
const hits = new Map<string, number[]>();

const isRateLimited = (ip: string): boolean => {
  const now = Date.now();
  const recent = (hits.get(ip) || []).filter((t) => now - t < RATE_LIMIT_WINDOW_MS);
  recent.push(now);
  hits.set(ip, recent);
  if (hits.size > 5000) hits.clear(); // crude guard against unbounded growth
  return recent.length > RATE_LIMIT_MAX;
};

/** Country the autocomplete is restricted to. JED services Australia only. */
const REGION_CODES = (process.env.PLACES_REGION_CODES || 'au')
  .split(',')
  .map((c) => c.trim().toLowerCase())
  .filter(Boolean);

const LANGUAGE_CODE = process.env.PLACES_LANGUAGE_CODE || 'en-AU';

type AddressComponent = {
  longText?: string;
  shortText?: string;
  types?: string[];
};

const pick = (components: AddressComponent[], type: string, short = false): string => {
  const match = components.find((c) => Array.isArray(c.types) && c.types.includes(type));
  if (!match) return '';
  return (short ? match.shortText : match.longText) || '';
};

/**
 * Collapse Google's component list into the shape GoHighLevel expects on a
 * contact record. AU addresses put the unit in `subpremise`, so "2/42 Smith St"
 * has to be reassembled by hand — Google never returns that as one line.
 */
const toStructuredAddress = (place: any) => {
  const components: AddressComponent[] = Array.isArray(place?.addressComponents)
    ? place.addressComponents
    : [];

  const unit = pick(components, 'subpremise');
  const streetNumber = pick(components, 'street_number');
  const street = pick(components, 'route');

  const streetPart = [streetNumber, street].filter(Boolean).join(' ');
  const addressLine1 = unit && streetPart ? `${unit}/${streetPart}` : streetPart;

  return {
    placeId: place?.id || '',
    formatted: place?.formattedAddress || '',
    unit,
    streetNumber,
    street,
    // `addressLine1` is what maps to GHL's `address1` contact field.
    addressLine1,
    suburb: pick(components, 'locality') || pick(components, 'sublocality') || '',
    state: pick(components, 'administrative_area_level_1', true),
    postcode: pick(components, 'postal_code'),
    country: pick(components, 'country'),
    countryCode: pick(components, 'country', true),
    lat: place?.location?.latitude ?? null,
    lng: place?.location?.longitude ?? null,
  };
};

export default async function handler(req: any, res: any) {
  const requestOrigin = req.headers?.origin;
  if (typeof res?.setHeader === 'function') setCors(res, requestOrigin);

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method Not Allowed' });
    return;
  }

  const apiKey = process.env.GOOGLE_PLACES_API_KEY || process.env.PLACES_API_KEY;
  if (!apiKey) {
    // Deliberately a 503, not a 500: the client treats this as "autocomplete is
    // unavailable" and silently degrades to a plain typed address field, so a
    // missing key can never block a lead from submitting.
    res.status(503).json({ error: 'Address lookup unavailable', reason: 'missing_api_key' });
    return;
  }

  const ip =
    (req.headers?.['x-forwarded-for'] || '').toString().split(',')[0].trim() ||
    req.socket?.remoteAddress ||
    'unknown';
  if (isRateLimited(ip)) {
    res.status(429).json({ error: 'Too many requests' });
    return;
  }

  try {
    let payload: any = req.body || {};
    if (typeof payload === 'string') {
      try {
        payload = JSON.parse(payload);
      } catch {
        res.status(400).json({ error: 'Invalid JSON body' });
        return;
      }
    }

    const action = String(payload.action || 'autocomplete');
    const sessionToken =
      typeof payload.sessionToken === 'string' && payload.sessionToken.length <= 128
        ? payload.sessionToken
        : undefined;

    if (action === 'autocomplete') {
      const input = String(payload.input || '').trim();
      // Below 3 characters the suggestions are noise and it is a wasted call.
      if (input.length < 3) {
        res.status(200).json({ suggestions: [] });
        return;
      }
      if (input.length > 200) {
        res.status(400).json({ error: 'Input too long' });
        return;
      }

      const googleResp = await fetch('https://places.googleapis.com/v1/places:autocomplete', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Goog-Api-Key': apiKey,
        },
        body: JSON.stringify({
          input,
          includedRegionCodes: REGION_CODES,
          includedPrimaryTypes: ['address'],
          languageCode: LANGUAGE_CODE,
          ...(sessionToken ? { sessionToken } : {}),
        }),
      });

      if (!googleResp.ok) {
        const details = await googleResp.text();
        console.error('[Places] autocomplete failed', googleResp.status, details);
        res.status(502).json({ error: 'Address lookup failed' });
        return;
      }

      const data = await googleResp.json();
      const suggestions = (data?.suggestions || [])
        .map((s: any) => s?.placePrediction)
        .filter(Boolean)
        .map((p: any) => ({
          placeId: p.placeId || '',
          primary: p.structuredFormat?.mainText?.text || p.text?.text || '',
          secondary: p.structuredFormat?.secondaryText?.text || '',
          full: p.text?.text || '',
        }))
        .filter((s: any) => s.placeId && s.primary);

      res.status(200).json({ suggestions });
      return;
    }

    if (action === 'details') {
      const placeId = String(payload.placeId || '').trim();
      if (!placeId || placeId.length > 256) {
        res.status(400).json({ error: 'Missing or invalid placeId' });
        return;
      }

      const url = new URL(`https://places.googleapis.com/v1/places/${encodeURIComponent(placeId)}`);
      url.searchParams.set('languageCode', LANGUAGE_CODE);
      if (sessionToken) url.searchParams.set('sessionToken', sessionToken);

      const googleResp = await fetch(url.toString(), {
        headers: {
          'X-Goog-Api-Key': apiKey,
          // Narrow field mask keeps this on the cheapest Place Details SKU.
          'X-Goog-FieldMask': 'id,formattedAddress,addressComponents,location',
        },
      });

      if (!googleResp.ok) {
        const details = await googleResp.text();
        console.error('[Places] details failed', googleResp.status, details);
        res.status(502).json({ error: 'Address lookup failed' });
        return;
      }

      const place = await googleResp.json();
      res.status(200).json({ address: toStructuredAddress(place) });
      return;
    }

    res.status(400).json({ error: 'Unknown action' });
  } catch (err: any) {
    console.error('[Places] Unexpected error', err?.message || err);
    res.status(500).json({ error: 'Unexpected error' });
  }
}
